doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 80
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs
    - migrations
    - wsgi.py
    - setup.py
    - flaskbb/configs
    - flaskbb/_compat.py
pep8:
  full: true
  disable:
    - E711
    - E712

pylint:
  disable:
    - too-few-public-methods
    - too-many-public-methods
    - too-many-locals
    - invalid-name
    - unused-argument
